# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Fri, 07 Apr 2017 00:16:01 +0000
*               @ALL          1
*               @user         8
opennic:teams:*	@mod	1
opennic:teams:*	@user	1
*	@mod	16
*	@readonly%2duser	1
